# Generated by Django 4.0.1 on 2022-01-31 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postlikes',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='postlikes',
            old_name='user_id',
            new_name='user',
        ),
    ]
