# Generated by Django 4.0.1 on 2022-02-01 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0002_rename_post_id_postlikes_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlikes',
            name='count',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
